### ISSUE TITLE
naiveproxy

### ISSUE THREAD

**Issue by Bryan2333** [sherlongqu/slcode#1]
[NaiveProxy](https://github.com/klzgrad/naiveproxy)

**Comment by sherlongqu** [comment]
> 

在哪个目录里呢？

**Comment by Bryan2333** [comment]
Qv2ray-v2.7.0-Windows\deployment\config\vcore

**Comment by sherlongqu** [comment]
> Qv2ray-v2.7.0-Windows\deployment\config\vcore

ok
